apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskernetes
  namespace: eks-flasker
  labels:
    app: flasker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flasker
  template:
    metadata:
      labels:
        app: flasker
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: flask
        image: nielsenjared/flasker:latest
        ports:
        - name: http
          containerPort: 5000
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux